import React from "react";

const Marquee = () => {
  return (
    <div className="app-marquee-container1">
      <div className="marquee-container1">
        <div className="marquee-subcontainer1 ">
          <div className="marquee-subitem-container1">
            <ul>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
            </ul>
          </div>

          <div className="marquee-subitem-container1">
            <ul>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
              <li>
                <span>Xis.ai</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Marquee;
