import Head from "next/head";
import StickyScroll from "./stickyscroll";
import { useEffect, useState, useRef, TouchEvent } from "react";
import { useRouter } from "next/router";
import Marquee from "@/components/Marquee";
import { Box, Typography } from "@mui/material";
import How from "@/components/howtowork";
import Image from "next/image";
import RoboticArm from "../assets/roboticArm.png";
import defectDetection from "../assets/defectDetection.png";
import xray2 from "../assets/xray2.png";
import 'intersection-observer';
import KeyboardDoubleArrowUpIcon from '@mui/icons-material/KeyboardDoubleArrowUp';

import { useAuth } from "@/common/authProvider";

export default function Home() {
  const [imageReveal, setImageReveal] = useState(0.5);
  const imageContainer = useRef(null);
  const handleRef = useRef(null);
  const controller = useRouter();

  const { accessToken } = useAuth();

  const slide = (xPosition) => {
    const containerBoundRect = imageContainer.current.getBoundingClientRect();

    if (xPosition <= containerBoundRect.left) {
      setImageReveal(0);
    } else if (xPosition >= containerBoundRect.right) {
      setImageReveal(1);
    } else {
      const positionInContainer = xPosition - containerBoundRect.left;
      const width = containerBoundRect.width;
      setImageReveal(positionInContainer / width);
    }
  };

  const handleTouchMove = (event) => {
    slide(event.touches[0].clientX);
  };

  const handleMouseDown = () => {
    const handle = handleRef.current;

    const handleMouseMove = (event) => {
      slide(event.clientX);
    };

    const handleMouseUp = () => {
      window.removeEventListener("mousemove", handleMouseMove);
      window.removeEventListener("mouseup", handleMouseUp);
    };

    window.addEventListener("mousemove", handleMouseMove);
    window.addEventListener("mouseup", handleMouseUp);
  };

  const doAnimations = () => {
    const offset = window.scrollY + window.innerHeight;
    const animatableElements = document.querySelectorAll(".animatable");

    animatableElements.forEach((element) => {
      if (
        element.getBoundingClientRect().top + element.offsetHeight - 20 <
        offset
      ) {
        element.classList.remove("animatable");
        element.classList.add("animated");
      }
    });
  };

  const handleScroll = () => {
    doAnimations();
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    window.addEventListener("load", doAnimations);

    return () => {
      window.removeEventListener("scroll", handleScroll);
      window.addEventListener("load", doAnimations);
    };
  }, []);

  const [scrollPosition, setScrollPosition] = useState(0);
  const [isSticky, setIsSticky] = useState(true);

  useEffect(() => {
    const handleScroll = () => {
      const newScrollPosition = window.scrollY;
      setScrollPosition(newScrollPosition);

      if (newScrollPosition <= 900) {
        setIsSticky(true);
      } else {
        setIsSticky(false);
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("showw");
        } else {
          entry.target.classList.remove("hidden");
        }
      });
    });

    const hiddenElements = document.querySelectorAll('.hiddenn');
    hiddenElements.forEach((element) => {
      observer.observe(element);
    });
  }); 

  const [showButton, setShowButton] = useState(false);


  
  useEffect(() => {
    const handleScroll = () => {
      const shouldShow = window.scrollY > 100; // Adjust the scroll distance as needed
      setShowButton(shouldShow);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return accessToken ? (
    <>
      <Head>
        <title>Xis.ai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      
      <div className="bg-[#111111] text-white relative overflow-hidden">
        <Box
          className="block bg-[#111111] object-cover w-[100vw] h-[90vh] max-w-[100vw] top-0 left-0 right-0 overflow-hidden pesudoMyClass"
          sx={{
            position: "relative",
            "&:before": {
              content: '""',
              position: "absolute",
              top: 0,
              left: 0,
              right: 0,
              width: "100%",
              height: "100%",
              background:
                "linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.7) 100%)",
              zIndex: 1,
              transition: "all 0.5s ease-in-out",
            },
          }}
        >
          <video
            className="w-[100vw] bg-[#111111] h-full opacity-80 fixed z-0 top-0 right-0 left-0 object-cover "
            autoPlay
            muted
            playsInline
            loop
            src="/xraylab.mp4"
          ></video>
          <div
            className="absolute top-2/3 w-full left-1/2 transform -translate-x-1/2 -translate-y-1/2  text-white text-center"
            style={{
              zIndex: 10,
            }}
          >
            <h1 className="text-5xl font-bold animated fadeInUp  ">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
            </h1>
            <p
              className="text-2lg mt-4 "
              style={{
                fontSize: "1.2rem",
              }}
            >
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis,
              voluptas?
            </p>
            <button className="rounded-md  hover:bg-white hover:text-black border px-2 py-1 mt-4">
              See an action
            </button>
          </div>
        </Box>
        <div className="text-white  block relative bg-[#111111] mt-0">
        <section
          className="text-white  block relative bg-[#111111] mt-0 "
          style={{
            marginTop: "0px",
          }}
        >
          <div className="justify-center text-white pb-6 text-center items-center w-full relative mx-auto z-10">
            <h1 className="text-5xl font-bold mb-20 pt-10">
              Benefits
            </h1>
            <div className="mb-12 sm:mb-10 lg:mb-36 relative mx-auto justify-center items-center z-10">
              <div className="min-h-[840px] hidden lg:block relative mx-auto justify-center items-center text-center">
                <div className="w-[30%] h-[60%] absolute top-[18%] left-24 rounded">
                  <Image
                    src="/generateai.jpg"
                    width={5501}
                    height={5001}
                    className="transform shadow-2xl shadow-sky-400 rounded-3xl animatable bounceInLeft  text-transparent custom-transform-style inline-block h-full max-w-full translate-x-0 translate-y-0 scale-100 rotate-0 skew-x-0 skew-y-0 opacity-100"
                  />
                </div>
                <div className="w-[73%] h-[50%] absolute top-0 left-[20%]">
                  <Image
                    src="/robotic2.jpeg"
                    width={656}
                    height={430}
                    className="transform shadow-2xl shadow-sky-400 rounded-3xl animatable fadeInDown text-transparent custom-transform-style inline-block h-full max-w-full translate-x-0 translate-y-0 scale-100 rotate-0 skew-x-0 skew-y-0 opacity-100"
                  />
                </div>
                <div className="w-[50%]  absolute -bottom-[4%] left-[25%]">
                  <Image
                    src="/robotic1.jpeg"
                    width={450}
                    height={400}
                    className="transform shadow-2xl shadow-sky-400  animatable fadeInUp rounded-3xl  text-transparent custom-transform-style inline-block h-full max-w-full translate-x-0 translate-y-0 scale-100 rotate-0 skew-x-0 skew-y-0 opacity-100"
                  />
                </div>
                <div className="w-[50%] h-[60%]  absolute -bottom-[1%]  -right-[4%]">
                  <Image
                    src="/aicase.jpg"
                    width={480}
                    height={680}
                    className="transform shadow-2xl shadow-sky-400  rounded-3xl animatable bounceInRight text-transparent custom-transform-style inline-block h-full max-w-full translate-x-0 translate-y-0 scale-100 rotate-0 skew-x-0 skew-y-0 opacity-100"
                  />
                </div>
              </div>
              <Image
                src="/fourpics.png"
                width={512}
                height={680}
                className="block w-[785px] object-cover mx-auto lg:hidden max-w-full"
              />
            </div>
            <Image
              src="/img5.svg"
              width={1096}
              height={680}
              className="-z-[1] max-w-none absolute top-0 left-[28%] pointer-events-none"
            />
          </div>
          <section className="text-white hiddenn py-24  body-font z-10">
            <div className="container px-5 mx-auto z-10 animatable fadeInUp ">
              <div className="w-20 h-20 inline-flex items-center   justify-center  bg-gray-800 rounded-lg text-white mb-5 flex-shrink-0">
                <svg
                  fill="none"
                  stroke="currentColor"
                  strokeLineCap="round"
                  strokeLineJoin="round"
                  strokeWidth="2"
                  className="w-10 h-10"
                  viewBox="0 0 24 24"
                >
                  <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                </svg>
              </div>
              <div className="flex flex-wrap -m-4">
                <div className="p-4 md:w-1/2 w-full">
                  <div className="h-full p-4 rounded">
                    <h1 className="mb-4 text-2xl font-medium ">
                      Get chain visibility
                    </h1>
                    <p className="mb-8 font-medium ">
                      Get insights from every part of the package journey
                    </p>

                    <p className="leading-relaxed flex mb-6 justify-start items-baseline  ">
                      <Image
                        src="/circle.svg"
                        width={10}
                        height={10}
                        className="mr-4"
                      />{" "}
                      Synth chartreuse iPhone lomo cray raw denim brunch
                      everyday carry.
                    </p>
                    <p className="leading-relaxed flex mb-6 justify-start items-baseline ">
                      <Image
                        src="/circle.svg"
                        width={10}
                        height={10}
                        className="mr-4"
                      />{" "}
                      Synth chartreuse iPhone lomo cray raw denim brunch
                      everyday carry.
                    </p>
                    <p className="leading-relaxed flex mb-6 justify-start items-baseline ">
                      <Image
                        src="/circle.svg"
                        width={10}
                        height={10}
                        className="mr-4 "
                      />{" "}
                      Synth chartreuse iPhone lomo cray raw denim brunch
                      everyday carry.
                    </p>
                  </div>
                </div>
                <div className="p-4 md:w-1/2 w-full">
                  <div className="h-full p-4 rounded">
                    <h1 className="md:mb-24 "></h1>

                    <p className="leading-relaxed flex mb-6 justify-start items-baseline ">
                      <Image
                        src="/circle.svg"
                        width={10}
                        height={10}
                        className="mr-4"
                      />{" "}
                      Synth chartreuse iPhone lomo cray raw denim brunch
                      everyday carry.
                    </p>
                    <p className="leading-relaxed flex mb-6 justify-start items-baseline  ">
                      <Image
                        src="/circle.svg"
                        width={10}
                        height={10}
                        className="mr-4"
                      />{" "}
                      Synth chartreuse iPhone lomo cray raw denim brunch
                      everyday carry.
                    </p>
                    <p className="leading-relaxed flex mb-6 justify-start items-baseline  ">
                      <Image
                        src="/circle.svg"
                        width={10}
                        height={10}
                        className="mr-4 "
                      />{" "}
                      Synth chartreuse iPhone lomo cray raw denim brunch
                      everyday carry.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="container px-5  mx-auto">
              <div className="flex flex-wrap -m-4">
                <div className="p-4 md:w-1/3">
                  <div className="flex rounded-lg h-full p-8 flex-col animatable fadeInUp  ">
                    <div className="flex items-center mb-8">
                      <div className="w-20 h-20 inline-flex items-center justify-center  bg-gray-800 rounded-lg text-white mb-5 flex-shrink-0">
                        <svg
                          fill="none"
                          stroke="currentColor"
                          strokeLineCap="round"
                          strokeLineJoin="round"
                          strokeWidth="2"
                          className="w-10 h-10"
                          viewBox="0 0 24 24"
                        >
                          <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                      </div>
                    </div>

                    <div className="flex-grow ">
                      <h2 className=" text-2xl font-medium mb-4 ">
                        Eliminate human errors
                      </h2>
                      <p className="leading-relaxed font-medium mb-4 ">
                        Blue bottle crucifix vinyl post-ironic four dollar toast
                        vegan taxidermy. Gastropub indxgo juice poutine.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="p-4 md:w-1/3">
                  <div className="flex rounded-lg h-full p-8 flex-col animatable fadeInUp ">
                    <div className="flex items-center mb-8">
                      <div className="w-20 h-20 inline-flex items-center justify-center  bg-gray-800 rounded-lg text-white mb-5 flex-shrink-0">
                        <svg
                          fill="none"
                          stroke="currentColor"
                          strokeLineCap="round"
                          strokeLineJoin="round"
                          strokeWidth="2"
                          className="w-10 h-10"
                          viewBox="0 0 24 24"
                        >
                          <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                          <circle cx="12" cy="7" r="4"></circle>
                        </svg>
                      </div>
                    </div>

                    <div className="flex-grow">
                      <h2 className=" text-2xl font-medium mb-4">
                        Increase customer loyalty
                      </h2>
                      <p className="leading-relaxed font-medium mb-4">
                        Blue bottle crucifix vinyl post-ironic four dollar toast
                        vegan taxidermy. Gastropub indxgo juice poutine.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="p-4 md:w-1/3 ">
                  <div className="flex rounded-lg h-full  p-8 flex-col animatable fadeInUp ">
                    <div className="flex items-center mb-8">
                      <div className="w-20 h-20 inline-flex items-center justify-center  bg-gray-800 rounded-lg text-white mb-5 flex-shrink-0">
                        <svg
                          fill="none"
                          stroke="currentColor"
                          strokeLineCap="round"
                          strokeLineJoin="round"
                          strokeWidth="2"
                          className="w-10 h-10"
                          viewBox="0 0 24 24"
                        >
                          <circle cx="6" cy="6" r="3"></circle>
                          <circle cx="6" cy="18" r="3"></circle>
                          <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12"></path>
                        </svg>
                      </div>
                    </div>

                    <div className="flex-grow ">
                      <h2 className=" text-2xl font-medium mb-4">
                        Fast time to value
                      </h2>
                      <p className="leading-relaxed font-medium mb-4">
                        Blue bottle crucifix vinyl post-ironic four dollar toast
                        vegan taxidermy. Gastropub indxgo juice poutine.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                      <p className="leading-relaxed flex mb-6 justify-start items-baseline">
                        <Image
                          src="/circle.svg"
                          width={10}
                          height={10}
                          className="mr-4"
                        />{" "}
                        Synth chartreuse iPhone lomo cray raw denim brunch
                        everyday carry.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </section>

        <section className="text-white block relative bg-[#111111] -my-1 ">
          <div className="container px-5 py-24 mx-auto animatable fadeInUp ">
            <div className="justify-center items-center text-center mb-16 text-5xl font-bold">
              Case Studies
            </div>
            <div className="flex hiddenn flex-wrap -mx-4 -mb-10 text-center">
              <div className="sm:w-1/2 mb-10 px-4 relative min-h-[1px]  elementor-element p-[1em]">
                <div className="rounded-lg h-[68%] overflow-hidden">
                  <Image
                    width={400}
                    height={400}
                    alt="content"
                    className="object-cover h-full object-center w-full"
                    src="/defectDetection.png"
                  />
                </div>
                <h2 className="title-font text-2xl font-medium mt-6 mb-6">
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                  Fuga, ea.
                </h2>
                <button className="inline-flex text-white bg-gray-800 border-0 py-2 px-6 focus:outline-none  rounded-xl text-lg">
                  API Reference
                </button>
              </div>
              <div className="sm:w-1/2 w-full mb-10 px-4 relative min-h-[1px] flex elementor-element p-[1em] ">
                <div className="rounded-lg overflow-hidden elementor-widget-wrap flex">
                  <div className="elementor-element  elementor-widget">
                    <div className="elementor-widget-container ">
                      <div className="twentytwenty-wrapper twentytwenty-horizontal">
                        <div
                          ref={imageContainer}
                          className="twentytwenty-container rounded-xl w-full h-[400.672px]"
                        >
                          <img
                            decoding="async"
                            style={{
                              clipPath: `polygon(0 0, ${
                                imageReveal * 100
                              }% 0, ${imageReveal * 100}% 100%, 0 100%)`,
                            }}
                            className="twentytwenty-before h-full pafe-before-after-image-comparison-slider__item pafe-before-after-image-comparison-slider__item--before"
                            src="https://www.tomomi-research.com/wp-content/uploads/2023/03/live-img-2022-09-23-14-11-58--jpg.webp"
                          />
                          <img
                            decoding="async"
                            className="custom-clip2 h-full pafe-before-after-image-comparison-slider__item pafe-before-after-image-comparison-slider__item--after twentytwenty-after"
                            src="https://www.tomomi-research.com/wp-content/uploads/2023/03/surface-normal-img-2022-09-23-14-11-58--jpg.webp"
                          />
                          <div className="twentytwenty-overlay">
                            <div
                              className="twentytwenty-before-label"
                              data-content="Xray"
                            ></div>
                            <div
                              className="twentytwenty-after-label"
                              data-content="Xray"
                            ></div>
                          </div>
                          <div
                            onMouseDown={handleMouseDown}
                            onTouchMove={handleTouchMove}
                            ref={handleRef}
                            style={{
                              touchAction: "none",
                              position: "absolute",
                              left: `${imageReveal * 100}%`,
                              cursor: "ew-resize",
                            }}
                            className="twentytwenty-handle "
                          >
                            <span className="twentytwenty-left-arrow"></span>
                            <span className="twentytwenty-right-arrow"></span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <How />
        <section className="text-white block relative dark:bg-gray-900 -my-1 ">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center animatable fadeInUp ">
            <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
              <h1 className="title-font sm:text-5xl sm:font-bold text-3xl mb-10 font-medium ">
                Features
              </h1>
              <p className="mb-10 hiddenn leading-relaxed w-1/2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam,
                quasi exercitationem temporibus minus quos dicta rem quis
                debitis repudiandae ipsum.
              </p>
              <div className="flex hiddenn justify-center">
                <button className="inline-flex text-white bg-gray-800 border-0 py-2 px-6 focus:outline-none  rounded-xl text-lg">
                  API Reference
                </button>
              </div>
            </div>
          </div>
        </section>
        <section className="text-white hiddenn block relative bg-[#111111] -my-1">
          <div className="container px-5 py-24 mx-auto animatable fadeInUp ">
            <div className="flex flex-wrap sm:-m-4 pb-28   -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">
              <div className="p-4 md:w-1/3 flex">
                <div className="w-20 h-20 inline-flex items-center justify-center rounded-lg bg-gray-800  text-white mb-4 flex-shrink-0">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLineCap="round"
                    strokeLineJoin="round"
                    strokeWidth="2"
                    className="w-10 h-10"
                    viewBox="0 0 24 24"
                  >
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                </div>
                <div className="flex-grow pl-6">
                  <h2 className="text-4xl title-font font-medium mb-10">
                    Label OCR API
                  </h2>
                  <p className="leading-relaxed text-base">
                    Have smartphones and camera devices extract information from
                    any package label.
                  </p>
                </div>
              </div>
              <div className="p-4 md:w-1/3 flex">
                <div className="w-20 h-20 inline-flex items-center justify-center rounded-lg bg-gray-800  text-white mb-4 flex-shrink-0">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLineCap="round"
                    strokeLineJoin="round"
                    strokeWidth="2"
                    className="w-10 h-10"
                    viewBox="0 0 24 24"
                  >
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                </div>
                <div className="flex-grow pl-6">
                  <h2 className="text-4xl title-font font-medium mb-10">
                    Label OCR API
                  </h2>
                  <p className="leading-relaxed text-base">
                    Have smartphones and camera devices extract information from
                    any package label.
                  </p>
                </div>
              </div>
              <div className="p-4 md:w-1/3 flex">
                <div className="w-20 h-20 inline-flex items-center justify-center rounded-lg bg-gray-800  text-white mb-4 flex-shrink-0">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLineCap="round"
                    strokeLineJoin="round"
                    strokeWidth="2"
                    className="w-10 h-10"
                    viewBox="0 0 24 24"
                  >
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                </div>
                <div className="flex-grow pl-6">
                  <h2 className="text-4xl title-font font-medium mb-10">
                    Label OCR API
                  </h2>
                  <p className="leading-relaxed text-base">
                    Have smartphones and camera devices extract information from
                    any package label.
                  </p>
                </div>
              </div>
            </div>
            <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">
              <div className="p-4 md:w-1/3 flex">
                <div className="w-20 h-20 inline-flex items-center justify-center rounded-lg bg-gray-800  text-white mb-4 flex-shrink-0">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLineCap="round"
                    strokeLineJoin="round"
                    strokeWidth="2"
                    className="w-10 h-10"
                    viewBox="0 0 24 24"
                  >
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                </div>
                <div className="flex-grow pl-6">
                  <h2 className="text-4xl title-font font-medium mb-10">
                    Label OCR API
                  </h2>
                  <p className="leading-relaxed text-base">
                    Have smartphones and camera devices extract information from
                    any package label.
                  </p>
                </div>
              </div>
              <div className="p-4 md:w-1/3 flex">
                <div className="w-20 h-20 inline-flex items-center justify-center rounded-lg bg-gray-800  text-white mb-4 flex-shrink-0">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLineCap="round"
                    strokeLineJoin="round"
                    strokeWidth="2"
                    className="w-10 h-10"
                    viewBox="0 0 24 24"
                  >
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                </div>
                <div className="flex-grow pl-6">
                  <h2 className="text-4xl title-font font-medium mb-10">
                    Label OCR API
                  </h2>
                  <p className="leading-relaxed text-base">
                    Have smartphones and camera devices extract information from
                    any package label.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      </div>
      <div  className="z-50" style={{ position: 'relative' }}>
        <div  className="z-50" style={{ position: 'fixed', bottom: '10%', right: '3%', }}>
          <button
          className="z-50"
            style={{ backgroundColor: '#363636', padding: '10px 10px', borderRadius: "10px", color: '#fff' , transition : '0.5s ease-in-out',opacity: showButton ? 1 : 0 }}
            onClick={scrollToTop}
          >
          <KeyboardDoubleArrowUpIcon/>
          </button>
        </div>
      </div>
    </>
  ) : (
    <>
      <Head>
        <title>Xis.ai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Box
        sx={{
          height: "100vh",
          width: "100%",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
        }}
      >
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "30%",
            width: "35%",
            flexDirection: "column",
          }}
        >
          <Typography>Permission Denied.</Typography>
          <Typography>Please Login to continue.</Typography>
          <button
            onClick={(_) => {
              controller.push("/");
            }}
            className="w-full lg:w-1/2 text-white bg-sky-500 hover:bg-sky-500 mt-10 focus:ring-1 focus:outline-none focus:ring-sky-500 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-sky-500 dark:hover:bg-sky-500 dark:focus:ring-sky-500"
          >
            Login
          </button>
        </Box>
      </Box>
    </>
  );
}
